### ISSUE TITLE
x509: certificate signed by unknown authority when trying to unseal vault

### ISSUE THREAD

**Issue by AlexMussell** [starkandwayne/shield-boshrelease#161]
Probably an extension of a previous issue (#153), however I am unsure if it will be being watched by the person who solved it.

After deployment, i need to manually and initialise the vault using -tls-skip-verify. Here is the vault job deployment:

**The job:**

```     
jobs:
  - name: core
    properties:  
       vault:
          tls:
            ca:          ((vault-tls.ca))
            certificate: ((vault-tls.certificate))
            key:         ((vault-tls.private_key))
```

**The variables:**

```
variables: 
 - name: vault-ca
    type: certificate
    options:
      is_ca: true
      common_name: vaultca

  - name: vault-tls
    type: certificate
    options:
      ca: vault-ca
      common_name: vault
      extended_key_usage:
        - client_auth
        - server_auth
      alternative_names:
        - 127.0.0.1
        - "*.vault.default.shield.bosh"
```

I shouldn't need to update the release to accommodate for the flag. Leading me to believe that I am doing something wrong. This issue seems to reappear and leads to the same issue as (#153).  That issue appears after unsealing the vault with ./vault unseal -tls-skip-verify. Any advice on either issue would be appreciated.
