### ISSUE TITLE
Ability to add multiple stores/retention policies/schedules & targets to SHIELD

### ISSUE THREAD

**Issue by karampok** [starkandwayne/shield-boshrelease#33]
Hi, 
since we are using bosh,  we need everything to be deployed through the bosh deployment manifest and not have any manual operation on the API. Currently it is only possible to add a single store (or schedule or retention policy). We would like to extend that.

For example to have something like that in the deployment manifests

```
shield:
  schedules:
       daily: daily 2am
       monthly: 2st sunday at 0am
       weekly: sundays 9am
```

which will create

```
shield  list  schedules
Using https://10.244.2.2:443 (default) as SHIELD backend

Name     Summary  Frequency / Interval (UTC)
====     =======  ==========================
daily             daily 2am
monthly           2st sunday at 0am
weekly            sundays 9am
```

Is it something you would like to integrate ?
