### ISSUE TITLE
Dynamically specify job-name when merging templates

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/shield-boshrelease#46]
We have shield deployed to multiple environments and configure the agent job at site level as follows:
```
properties:
  shield:
    job:
      name: (( grab name))
      <etc>
```

Now that only plural version of `jobs` key is supported we cannot dynamically determin the job name when merging the templates via spruce / genesis.

**Comment by jhunt** [comment]
Can you provide more of your templates?  I have a feeling you can do this with `(( inline ))`

**Comment by bodymindarts** [comment]
yeah I didn’t explain it well sorry (writting tickets while on client call)…
the issue is we can do:
```job:
  name: (( grab <some-name> ))
```
but with the pluralized version it needs to be:
```jobs:
  <some-name>:
    (etc)
```

is there a way to use spruce to get a _grabbed_ field and have it be the _key_

**Comment by jhunt** [comment]
Sadly, there is not.  Feel free to open a PR against https://github.com/geofffranks/spruce to see if it can be modified to do so.

In the meantime, what if we added an optional `name:` attribute to all of the entries, and have that 'default' to the key if not specified?

So:

```
properties:
  shield:
    jobs:
      default:
        name: (( grab name ))
        # etc.
```

**Comment by bodymindarts** [comment]
So when specifying many jobs like:
```
properties:
  shield:
    jobs:
      joba:
       name: a-job
      jobb:
        name: b-job
```
The value under the `name:` attribute would win over the key that the attrs are under?
