### ISSUE TITLE
Can't find link with type 'sql' for job 'shield' in deployment 

### ISSUE THREAD

**Issue by karampok** [starkandwayne/shield-boshrelease#92]
Greetings,
we are trying to deploy the new version of SHIELD (7.0.1), and our deployment manifest seems broken.  The error we are getting is the following

```
 Started preparing deployment > Preparing deployment. Failed: Unable to process links for deployment. Errors are:
  - Can't find link with type 'sql' for job 'shield' in deployment 'shield-yyy' (00:00:00)
```

The difference in our manifest is that we are adding the database url directly instead of using links and that there no deployment offering such a link. The manifest looks like that

```
  - name: shield-daemon
    properties:
      shield:
        daemon:
          auth:
            api_keys:
              autoprovision: XXXXX
            basic_password: YYYYY
            basic_user: admin
          database:
            db: shielddb
            host: 10.x.y.z
            password: zzzzzzzz
            port: 3306
            type: mysql
            username: shieldadmin
          ssh_private_key: |
            -----BEGIN RSA PRIVATE KEY-----
```

What do you think of having the sql link optional in the spec file?
Also shield-daemon is starting even if the database access is not established (monit summary give running), is that on purpose?

Thanks!
